### ISSUE TITLE
Adding features

### ISSUE THREAD

**Issue by atisamStellar** [HeT-Delwadiya/MyThoughts-Android-App#1]
1. Words count
2. Sentiment Analysis
3. Auto correct
4. Login screen issue

**Comment by het-delwadiya** [comment]
I moved to web development but contributors are most welcome :)

**Comment by atisamStellar** [comment]
i want to contribute

**Comment by atisamStellar** [comment]
Give me access

**Comment by het-delwadiya** [comment]
Done

**Comment by atisamStellar** [comment]
New features added now

**Comment by atisamStellar** [comment]
Bugs fixed
